### ISSUE TITLE
Pulumi segfaults when the `Dir` of a `Local.Command` is a file

### ISSUE THREAD

**Issue by Smaug123** [pulumi/pulumi-command#182]
### What happened?

Due to programmer error, I set a file as the working directory for a Local.Command, and the following was the result. This appears to be consistently the behaviour however far I've minimised the repro. (I'm in .NET, if that's relevant.)

```
bash-5.2$ pulumi up --stack staging  --yes
Previewing update (staging)

View Live: https://app.pulumi.com/Smaug123/PulumiWebServer/staging/previews/0746ad4f-8794-48eb-8f9d-a4219d625c5a

     Type                        Name                                                    Plan       
     pulumi:pulumi:Stack         PulumiWebServer-staging                                            
 +   ├─ command:local:Command    wait-for-ready-PulumiWebServer.Program+readyCommand@67  create     
 -   ├─ cloudflare:index:Record  calendar.staging-ipv6                                   delete     
 -   ├─ cloudflare:index:Record  staging.patrickstevens.co.uk-ipv6                       delete     
 -   ├─ cloudflare:index:Record  www.staging-cname                                       delete     
 -   ├─ cloudflare:index:Record  gitea.staging-ipv6                                      delete     
 -   ├─ cloudflare:index:Record  calendar.staging-ipv4                                   delete     
 -   ├─ cloudflare:index:Record  staging.patrickstevens.co.uk-ipv4                       delete     
 -   └─ cloudflare:index:Record  gitea.staging-ipv4                                      delete     


Resources:
    + 1 to create
    - 7 to delete
    8 changes. 2 unchanged

Updating (staging)

View Live: https://app.pulumi.com/Smaug123/PulumiWebServer/staging/updates/109

     Type                      Name                                                    Status                  Info
     pulumi:pulumi:Stack       PulumiWebServer-staging                                 **failed**              1 error; 23 messages
 +   └─ command:local:Command  wait-for-ready-PulumiWebServer.Program+readyCommand@67  **creating failed**     1 error


Diagnostics:
  pulumi:pulumi:Stack (PulumiWebServer-staging):
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10160e950]
    goroutine 8 [running]:
    github.com/pulumi/pulumi-command/provider/pkg/provider.(*commandContext).run(0x14000397a70, {0x10195c260?, 0x14000394640}, {0x14000040280, 0x3e}, 0x14000193548, {0x14000136100, 0x72})
    	/home/runner/work/pulumi-command/pulumi-command/provider/pkg/provider/command.go:164 +0x7c0
    github.com/pulumi/pulumi-command/provider/pkg/provider.(*command).RunCreate(0x14000397a70, {0x10195c260?, 0x14000394640?}, 0x101?, {0x14000136100?, 0x140000bb090?})
    	/home/runner/work/pulumi-command/pulumi-command/provider/pkg/provider/command.go:76 +0x48
    github.com/pulumi/pulumi-command/provider/pkg/provider.(*commandProvider).Create(0x14000181630, {0x10195c308?, 0x1400038f380?}, 0x14000118870)
    	/home/runner/work/pulumi-command/pulumi-command/provider/pkg/provider/provider.go:250 +0x6e8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1({0x10195c308, 0x1400038f380}, {0x1018ddf80?, 0x14000118870})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.38.0/proto/go/provider.pb.go:3725 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x10195c308, 0x1400038f080}, {0x1018ddf80, 0x14000118870}, 0x1400038a3c0, 0x14000398570)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x30c
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler({0x1019230e0?, 0x14000181630}, {0x10195c308, 0x1400038f080}, 0x14000380420, 0x1400026c9a0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.38.0/proto/go/provider.pb.go:3727 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0x140003308c0, {0x101961ce0, 0x14000404340}, 0x14000000120, 0x14000327830, 0x101eccbc0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.47.0/server.go:1283 +0xb50
    google.golang.org/grpc.(*Server).handleStream(0x140003308c0, {0x101961ce0, 0x14000404340}, 0x14000000120, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.47.0/server.go:1620 +0x82c
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.47.0/server.go:922 +0x84
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.47.0/server.go:920 +0x290

    error: update failed

  command:local:Command (wait-for-ready-PulumiWebServer.Program+readyCommand@67):
    error: error reading from server: EOF

Resources:
    2 unchanged
```

### Expected Behavior

Some kind of error saying "you fool, you gave me a file as the working directory - that's not a directory!".

### Steps to reproduce

```fsharp
namespace PulumiWebServer

open Pulumi

module Program =

    [<EntryPoint>]
    let main _argv =
        fun () ->
            let command =
                let args = Pulumi.Command.Local.CommandArgs ()
                args.Create <- Input.op_Implicit "echo hello"
                args.Dir <- Input.op_Implicit "/bin/sh"
                Pulumi.Command.Local.Command ("wait-for-ready", args)
            command.Stdout
            |> ignore
        |> Deployment.RunAsync
        |> Async.AwaitTask
        |> Async.RunSynchronously
```

### Output of `pulumi about`

```
bash-5.2$ pulumi about
running 'dotnet build -nologo .'
  Determining projects to restore...

  All projects are up-to-date for restore.

  PulumiWebServer -> /Users/patrick/Documents/GitHub/Pulumi/PulumiWebServer/bin/Debug/net7.0/PulumiWebServer.dll



Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.91

'dotnet build -nologo .' completed successfully
CLI          
Version      3.53.1
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME          VERSION
cloudflare    4.15.0
command       4.5.0
digitalocean  4.16.0
dotnet        unknown

Host     
OS       darwin
Version  13.1
Arch     arm64

This project is written in dotnet: executable='/nix/store/mpahmcl10nx3v4p3zj49jrbx4z9kwi42-dotnet-sdk-7.0.102/bin/dotnet' version='7.0.102'

Current Stack: Smaug123/PulumiWebServer/dev

TYPE                                URN
pulumi:pulumi:Stack                 urn:pulumi:dev::PulumiWebServer::pulumi:pulumi:Stack::PulumiWebServer-dev
pulumi:providers:digitalocean       urn:pulumi:dev::PulumiWebServer::pulumi:providers:digitalocean::default_4_14_0
digitalocean:index/sshKey:SshKey    urn:pulumi:dev::PulumiWebServer::digitalocean:index/sshKey:SshKey::default
digitalocean:index/droplet:Droplet  urn:pulumi:dev::PulumiWebServer::digitalocean:index/droplet:Droplet::nixos-server
pulumi:providers:cloudflare         urn:pulumi:dev::PulumiWebServer::pulumi:providers:cloudflare::default_4_9_0
cloudflare:index/record:Record      urn:pulumi:dev::PulumiWebServer::cloudflare:index/record:Record::www-cname
cloudflare:index/record:Record      urn:pulumi:dev::PulumiWebServer::cloudflare:index/record:Record::gitea-ipv6
cloudflare:index/record:Record      urn:pulumi:dev::PulumiWebServer::cloudflare:index/record:Record::gitea-ipv4
cloudflare:index/record:Record      urn:pulumi:dev::PulumiWebServer::cloudflare:index/record:Record::calendar-ipv6
cloudflare:index/record:Record      urn:pulumi:dev::PulumiWebServer::cloudflare:index/record:Record::calendar-ipv4
cloudflare:index/record:Record      urn:pulumi:dev::PulumiWebServer::cloudflare:index/record:Record::rss-ipv6
cloudflare:index/record:Record      urn:pulumi:dev::PulumiWebServer::cloudflare:index/record:Record::rss-ipv4
cloudflare:index/record:Record      urn:pulumi:dev::PulumiWebServer::cloudflare:index/record:Record::patrickstevens.co.uk-ipv6
cloudflare:index/record:Record      urn:pulumi:dev::PulumiWebServer::cloudflare:index/record:Record::patrickstevens.co.uk-ipv4
pulumi:providers:command            urn:pulumi:dev::PulumiWebServer::pulumi:providers:command::default_0_4_1
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::nix-infect
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::reboot-post-infect
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::write-user-config
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::write-flake
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::write-flake-lock
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::configure-users
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::configure-gitea-password
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::write-gitea-password
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::create-user-'radicale'
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::write-nginx-config
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::write-gitea-config
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::write-radicale-config
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::configure-radicale
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::configure-gitea
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::configure-nginx
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::radicale-gitconfig
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::radicale-gitignore
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::create-user-'tt_rss'
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::write-ttrss-config
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::configure-ttrss-password
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::configure-ttrss
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::configure-radicale-user
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::nixos-rebuild


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/Smaug123
User           Smaug123
Organizations  Smaug123, fsprojects

Dependencies:
NAME                 VERSION
FSharp.Core          7.0.0
Nager.PublicSuffix   2.4.0
Newtonsoft.Json      13.0.1
Pulumi               3.53.0
Pulumi.Cloudflare    4.15.0
Pulumi.Command       4.5.0
Pulumi.DigitalOcean  4.16.0

Pulumi locates its logs in /tmp/nix-shell.ok6EOv by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Thank you for reporting this, @Smaug123.

Despite what it looks like, it appears you are not on a current version of this provider. After digging around for a while, I discovered that we [erroneously published a `v4.5.0` tagged release last year](https://github.com/pulumi/pulumi-command/actions/workflows/release.yml).

Please try your program using `v0.7.0`; I tried it (albeit on typescript as I'm not a dotnet programmer) and received a proper error back from golang's `os.exec` library:

```
Diagnostics:
  command:local:Command (print):
    error: fork/exec /bin/sh: not a directory

  pulumi:pulumi:Stack (command-182-dev):
    error: update failed
```

I'm filing a followup issue for having an invalid version that is published and causing confusion - we want to make sure this doesn't happen to somebody else.

Thanks again for your very complete report. I will close this issue as fixed in the (true) current version.
