### ISSUE TITLE
Go panic after update 

### ISSUE THREAD

**Issue by jabbrwcky** [pulumi/pulumi-command#41]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I have a program that runs a command locally which worked up to the latest pulumi update.

Now the command finishes sucessfully, but the provider panics:

```
    panic: fatal: An assertion has failed
    goroutine 38 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assert(...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/go/common/util/contract/assert.go:26
    github.com/pulumi/pulumi/sdk/v3/go/common/util/mapper.(*mapper).EncodeValue(0x140001d7310, 0x0, 0x0, 0x1, 0x0, 0x0, 0x194)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/go/common/util/mapper/mapper_encode.go:71 +0xd0c
    github.com/pulumi/pulumi/sdk/v3/go/common/util/mapper.(*mapper).EncodeValue(0x140001d7310, 0x10331d8e0, 0x14000203980, 0x10332fa01, 0x10331d8e0, 0x14000203980, 0x10335ccc0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/go/common/util/mapper/mapper_encode.go:100 +0x5cc
    github.com/pulumi/pulumi/sdk/v3/go/common/util/mapper.(*mapper).EncodeValue(0x140001d7310, 0x103375bc0, 0x14000584c60, 0x10332fa01, 0x103375bc0, 0x14000584c60, 0x10335ccc0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/go/common/util/mapper/mapper_encode.go:116 +0x1ec
    github.com/pulumi/pulumi/sdk/v3/go/common/util/mapper.(*mapper).EncodeValue(0x140001d7310, 0x103375bc0, 0x14000584c30, 0x10332fa01, 0x103375bc0, 0x14000584c30, 0x10335ccc0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/go/common/util/mapper/mapper_encode.go:116 +0x1ec
    github.com/pulumi/pulumi/sdk/v3/go/common/util/mapper.(*mapper).EncodeValue(0x140001d7310, 0x103375bc0, 0x14000584bd0, 0x10332fa01, 0x103375bc0, 0x14000584bd0, 0x10335ccc0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/go/common/util/mapper/mapper_encode.go:116 +0x1ec
    github.com/pulumi/pulumi/sdk/v3/go/common/util/mapper.(*mapper).EncodeValue(0x140001d7310, 0x103375bc0, 0x14000584ba0, 0x10332fa01, 0x103375bc0, 0x14000584ba0, 0x10335ccc0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/go/common/util/mapper/mapper_encode.go:116 +0x1ec
    github.com/pulumi/pulumi/sdk/v3/go/common/util/mapper.(*mapper).EncodeValue(0x140001d7310, 0x103375bc0, 0x140005845d0, 0x10332fa01, 0x103375bc0, 0x140005845d0, 0x10335ccc0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/go/common/util/mapper/mapper_encode.go:116 +0x1ec
    github.com/pulumi/pulumi/sdk/v3/go/common/util/mapper.(*mapper).EncodeValue(0x140001d7310, 0x103375bc0, 0x14000584570, 0x1, 0x103375bc0, 0x14000584570, 0x194)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/go/common/util/mapper/mapper_encode.go:116 +0x1ec
    github.com/pulumi/pulumi/sdk/v3/go/common/util/mapper.(*mapper).EncodeValue(0x140001d7310, 0x10331d8e0, 0x1400000c018, 0x10331d801, 0x10331d8e0, 0x1400000c018, 0x96)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/go/common/util/mapper/mapper_encode.go:100 +0x5cc
    github.com/pulumi/pulumi/sdk/v3/go/common/util/mapper.(*mapper).EncodeValue(0x140001d7310, 0x1032f8880, 0x14000203a70, 0x1032e7501, 0x1032f8880, 0x14000203a70, 0x140001340d8)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/go/common/util/mapper/mapper_encode.go:92 +0x474
    github.com/pulumi/pulumi/sdk/v3/go/common/util/mapper.(*mapper).Encode(0x140001d7310, 0x103446440, 0x140001340c0, 0x140001340c0, 0x1400020e140, 0x3c)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/go/common/util/mapper/mapper_encode.go:46 +0x3e0
    github.com/pulumi/pulumi-command/provider/pkg/provider.(*commandProvider).Create(0x14000400bd0, 0x1034c9e48, 0x1400021b8c0, 0x140002045a0, 0x0, 0x0, 0x0)
    	/home/runner/work/pulumi-command/pulumi-command/provider/pkg/provider/provider.go:202 +0xae4
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1(0x1034c9e48, 0x1400021b8c0, 0x103443860, 0x140002045a0, 0x103452280, 0x103a03fa0, 0x1034c9e48, 0x1400021b8c0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/proto/go/provider.pb.go:2602 +0x7c
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x1034c9e48, 0x1400021ab10, 0x103443860, 0x140002045a0, 0x14000212300, 0x14000202408, 0x0, 0x0, 0x1034b6f08, 0x140001917c0)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x260
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler(0x103465660, 0x14000400bd0, 0x1034c9e48, 0x1400021ab10, 0x14000200720, 0x140001b38c0, 0x1034c9e48, 0x1400021ab10, 0x14000262a80, 0xa3c)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/proto/go/provider.pb.go:2604 +0x12c
    google.golang.org/grpc.(*Server).processUnaryRPC(0x1400039b880, 0x1034d2778, 0x14000102480, 0x1400024c240, 0x14000400c60, 0x1039c74a0, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1217 +0x3e8
    google.golang.org/grpc.(*Server).handleStream(0x1400039b880, 0x1034d2778, 0x14000102480, 0x1400024c240, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1540 +0xa50
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0x14000040060, 0x1400039b880, 0x1034d2778, 0x14000102480, 0x1400024c240)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:878 +0x94
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:876 +0x1f8
```

### Steps to reproduce

~~Not sure how to reproduce w/o context.~~

Run some command, i.e. `echo` with `triggers configured`:

```typescript
const k0sctrl = new cmd.local.Command("k0sctrl", {
    create: "echo helloworld", //"echo k0sctl apply --disable-telemetry",
    triggers: [
        k0sCtrlConfig.configuration
    ]
}, {
    dependsOn: [
        k0sCtrlConfig
    ]
})
```

causes this error,

```typescript
const k0sctrl = new cmd.local.Command("k0sctrl", {
    create: "echo helloworld", //"echo k0sctl apply --disable-telemetry",
}, {
    dependsOn: [
        k0sCtrlConfig
    ]
})
```

works.

* Command provider v0.0.3
* Pulumi version v3.25.0
* Language Typescript

Expected: Expected continued execution after executing external program
Actual: panic in provider

**Comment by ghostsquad** [comment]
what is `k0sCtrlConfig` and `k0sCtrlConfig.configuration` ?

**Comment by guineveresaenger** [comment]
Hi @jabbrwcky  -

I cannot repro this without knowing `k0sCtrlConfig` and `k0sCtrlConfig.configuration`.

As well, can you confirm that this is still an issue with the latest Pulumi patch release to v3.25.1?

**Comment by jabbrwcky** [comment]
`k0sCrtlConfig` is a dynamic provider to create a configuration file for [k0sctrl](https://github.com/k0sproject/k0sctl#configuration-file): 

https://gist.github.com/jabbrwcky/72b23057098bdd707b2c76c46150b615

```typescript
const k0sCtrlConfig = new k0s.CtrlConfiguration("clusterConfig", {
    metadata: {
        name: config.get("clustername"),
    },
    spec: {
        hosts: nodes.map((n) => {
            return {
                role: n.role,
                privateAddress: n.privateIp,
                installFlags: [
                    "--enable-cloud-provider",
                    "--profile=reservations",
                ],
                ssh: {
                    address: n.privateIp,
                    keyPath: "k0sbootstrap",
                    bastion: {
                        address: bastionHost.ipAddress,
                        user: "root",
                        keyPath: "k0sbootstrap",
                    }
                }
            };
        }),
        k0s: {
            version: "v1.21.9+k0s.0",
            config: {
                apiVersion: "k0s.k0sproject.io/v1beta1",
                kind: "Cluster",
                spec: {
                    api: {
                        externalAddress: apiServerRecord.fqdn,
                        sans: [
                            apiServerRecord.fqdn,
                            apiLoadBalancer.loadBalancer.ipv4,
                            apiLoadBalancer.network.ip,
                        ],
                    },
                    workerProfiles: [{
                        name: "reservations",
                        values: {
                            systemReserved: {
                                cpu: "100m",
                                memory: "100Mi",
                                "ephemeral-storage": "1Gi",
                            },
                            kubeReserved: {
                                memory: "1.8Gi",
                                cpu: "70m",
                                "ephemeral-storage": "1Gi",
                            }
                        }
                    }]
                }
            }
        }
    }
});

const yamlConf = pulumi.all([k0sCtrlConfig.configuration, k0sCtrlConfig.file]).apply(([c, f]) => {
    let cnt = stringify(c)
    fs.writeFileSync(f, cnt)
    return cnt
});
```

I could only reproduce the issue (regardless of Pulumi Version AFAICT) when I destroyed the entire stack and recreated everything from scratch - if I add the trigger once the configuration file has been created it causes no issues.

**Comment by lukehoban** [comment]
This was fixed with https://github.com/pulumi/pulumi/pull/9810.
