### ISSUE TITLE
Panic error

### ISSUE THREAD

**Issue by AMKamel** [pulumi/pulumi-command#68]
### What happened?

Running pulumi up with a command that was executing an ansible playbook, it run too many times before without reporting such a panic, maybe this is the second time I see a panic

### Steps to reproduce

`pulumi up --skip-preview`

### Expected Behavior

Run normally

### Actual Behavior

Got the following error
```
    panic: fatal: An assertion has failed
    goroutine 84 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.33.1/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assert(...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.33.1/go/common/util/contract/assert.go:26
    github.com/pulumi/pulumi/sdk/v3/go/common/util/mapper.(*mapper).EncodeValue(0xc000615340, 0x0, 0x0, 0x1, 0x0, 0x0, 0x194)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.33.1/go/common/util/mapper/mapper_encode.go:71 +0x107f
    github.com/pulumi/pulumi/sdk/v3/go/common/util/mapper.(*mapper).EncodeValue(0xc000615340, 0xca90c0, 0xc00011c018, 0xca9001, 0xca90c0, 0xc00011c018, 0x96)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.33.1/go/common/util/mapper/mapper_encode.go:100 +0x771
    github.com/pulumi/pulumi/sdk/v3/go/common/util/mapper.(*mapper).EncodeValue(0xc000615340, 0xc83c80, 0xc0006a68b8, 0xc72101, 0xc83c80, 0xc0006a68b8, 0xc00014a8d8)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.33.1/go/common/util/mapper/mapper_encode.go:92 +0x5d1
    github.com/pulumi/pulumi/sdk/v3/go/common/util/mapper.(*mapper).Encode(0xc000615340, 0xdef340, 0xc00014a8c0, 0xc00014a8c0, 0xc0001ba0e0, 0x6e)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.33.1/go/common/util/mapper/mapper_encode.go:46 +0x52a
    github.com/pulumi/pulumi-command/provider/pkg/provider.(*commandProvider).Create(0xc000344c90, 0xf52208, 0xc000500f90, 0xc000694b90, 0x0, 0x0, 0x0)
    	/home/runner/work/pulumi-command/pulumi-command/provider/pkg/provider/provider.go:215 +0x1075
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1(0xf52208, 0xc000500f90, 0xdd2960, 0xc000694b90, 0xf52208, 0xc000500f90, 0xf5c400, 0x14b4100)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.33.1/proto/go/provider.pb.go:2614 +0x89
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0xf52208, 0xc000500f90, 0xdd2960, 0xc000694b90, 0xc0006ae600, 0xc0006a6840, 0x0, 0x0, 0xf3f840, 0xc000089750)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2de
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler(0xdfdb80, 0xc000344c90, 0xf52208, 0xc000500c90, 0xc000502540, 0xc0000318c0, 0xf52208, 0xc000500c90, 0xc0003eb000, 0x7a4)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.33.1/proto/go/provider.pb.go:2616 +0x150
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003296c0, 0xf5a778, 0xc0002f2ea0, 0xc000606c60, 0xc000344d20, 0x1477540, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1282 +0x52b
    google.golang.org/grpc.(*Server).handleStream(0xc0003296c0, 0xf5a778, 0xc0002f2ea0, 0xc000606c60, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1619 +0xd0c
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0003d4360, 0xc0003296c0, 0xf5a778, 0xc0002f2ea0, 0xc000606c60)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:921 +0xab
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:919 +0x1fd
 
    error: update failed

```

### Versions used

```
CLI          
Version      3.33.2
Go Version   go1.17.10
Go Compiler  gc

Plugins
NAME           VERSION
cloudinit      1.3.0
command        0.2.0
nodejs         unknown
pulumiservice  0.1.3
random         4.7.0
vault          5.5.0

Host     
OS       ubuntu
Version  22.04
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AMKamel** [comment]
Now it happend for the second time in a row
```
  pulumi:pulumi:Stack (dev):
    panic: fatal: An assertion has failed
    goroutine 16 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.33.1/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assert(...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.33.1/go/common/util/contract/assert.go:26
    github.com/pulumi/pulumi/sdk/v3/go/common/util/mapper.(*mapper).EncodeValue(0xc000493340, 0x0, 0x0, 0x1, 0x0, 0x0, 0x194)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.33.1/go/common/util/mapper/mapper_encode.go:71 +0x107f
    github.com/pulumi/pulumi/sdk/v3/go/common/util/mapper.(*mapper).EncodeValue(0xc000493340, 0xca90c0, 0xc00012e090, 0xca9001, 0xca90c0, 0xc00012e090, 0x96)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.33.1/go/common/util/mapper/mapper_encode.go:100 +0x771
    github.com/pulumi/pulumi/sdk/v3/go/common/util/mapper.(*mapper).EncodeValue(0xc000493340, 0xc83c80, 0xc00012fc80, 0xc72101, 0xc83c80, 0xc00012fc80, 0xc000512248)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.33.1/go/common/util/mapper/mapper_encode.go:92 +0x5d1
    github.com/pulumi/pulumi/sdk/v3/go/common/util/mapper.(*mapper).Encode(0xc000493340, 0xdef340, 0xc000512230, 0xc000512230, 0xc00004c0e0, 0x6e)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.33.1/go/common/util/mapper/mapper_encode.go:46 +0x52a
    github.com/pulumi/pulumi-command/provider/pkg/provider.(*commandProvider).Create(0xc0002e0c90, 0xf52208, 0xc0004b9d10, 0xc00052a3c0, 0x0, 0x0, 0x0)
    	/home/runner/work/pulumi-command/pulumi-command/provider/pkg/provider/provider.go:215 +0x1075
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1(0xf52208, 0xc0004b9d10, 0xdd2960, 0xc00052a3c0, 0xf52208, 0xc0004b9d10, 0xf5c400, 0x14b4100)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.33.1/proto/go/provider.pb.go:2614 +0x89
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0xf52208, 0xc0004b9d10, 0xdd2960, 0xc00052a3c0, 0xc000141400, 0xc00012fc08, 0x0, 0x0, 0xf3f840, 0xc00011f740)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2de
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler(0xdfdb80, 0xc0002e0c90, 0xf52208, 0xc0004b9a10, 0xc00013d980, 0xc000141880, 0xf52208, 0xc0004b9a10, 0xc00018c000, 0x7a4)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.33.1/proto/go/provider.pb.go:2616 +0x150
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002c56c0, 0xf5a778, 0xc0004c0000, 0xc0004d99e0, 0xc0002e0d20, 0x1477540, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1282 +0x52b
    google.golang.org/grpc.(*Server).handleStream(0xc0002c56c0, 0xf5a778, 0xc0004c0000, 0xc0004d99e0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1619 +0xd0c
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000494040, 0xc0002c56c0, 0xf5a778, 0xc0004c0000, 0xc0004d99e0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:921 +0xab
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:919 +0x1fd
 
    error: update failed
 
  command:local:Command (dev):
    error: error reading from server: EOF
```

yet I was doing debug level logs and ansible playbook didn't fail, ansible final report:
```
I0608 10:21:09.205767  491029 eventsink.go:59]     "stats": {
I0608 10:21:09.205914  491029 eventsink.go:59]         "163.172.251.59": {
I0608 10:21:09.206051  491029 eventsink.go:59]             "changed": 15,
I0608 10:21:09.206208  491029 eventsink.go:59]             "failures": 0,
I0608 10:21:09.206342  491029 eventsink.go:59]             "ignored": 0,
I0608 10:21:09.206465  491029 eventsink.go:59]             "ok": 18,
I0608 10:21:09.206582  491029 eventsink.go:59]             "rescued": 0,
I0608 10:21:09.206706  491029 eventsink.go:59]             "skipped": 0,
I0608 10:21:09.206837  491029 eventsink.go:59]             "unreachable": 0
I0608 10:21:09.206961  491029 eventsink.go:59]         },
I0608 10:21:09.207088  491029 eventsink.go:59]         "195.154.83.208": {
I0608 10:21:09.207208  491029 eventsink.go:59]             "changed": 4,
I0608 10:21:09.207330  491029 eventsink.go:59]             "failures": 0,
I0608 10:21:09.207460  491029 eventsink.go:59]             "ignored": 0,
I0608 10:21:09.207575  491029 eventsink.go:59]             "ok": 6,
I0608 10:21:09.207691  491029 eventsink.go:59]             "rescued": 0,
I0608 10:21:09.207815  491029 eventsink.go:59]             "skipped": 0,
I0608 10:21:09.207956  491029 eventsink.go:59]             "unreachable": 0
I0608 10:21:09.208087  491029 eventsink.go:59]         },
I0608 10:21:09.208211  491029 eventsink.go:59]         "localhost": {
I0608 10:21:09.208337  491029 eventsink.go:59]             "changed": 5,
I0608 10:21:09.208459  491029 eventsink.go:59]             "failures": 0,
I0608 10:21:09.208574  491029 eventsink.go:59]             "ignored": 0,
I0608 10:21:09.208694  491029 eventsink.go:59]             "ok": 6,
I0608 10:21:09.208818  491029 eventsink.go:59]             "rescued": 0,
I0608 10:21:09.208946  491029 eventsink.go:59]             "skipped": 0,
I0608 10:21:09.209074  491029 eventsink.go:59]             "unreachable": 0
I0608 10:21:09.209201  491029 eventsink.go:59]         }
I0608 10:21:09.209320  491029 eventsink.go:59]     }
I0608 10:21:09.209459  491029 eventsink.go:59] }
```

**Comment by AMKamel** [comment]
This seems related to issue https://github.com/pulumi/pulumi-command/issues/41

After destroying then removing `triggers`, creating again run without issues!

**Comment by jkisk** [comment]
working with @pgavlin to get this fixed, rolled out, and released

**Comment by chrisui** [comment]
Any chance we can get a release published for this? It's a big blocker for us as we are making use of pulumi/command for syncing s3 sites but encounter a panic error consistently.

**Comment by chrisui** [comment]
in case useful:

```
command:local:Command (pre-dev-docs-sync):
error: transport is closing
command:local:Command (pre-sto-site-sync):
error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:43349: connect: connection refused"
pulumi:pulumi:Stack (platform-preview):
error: update failed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb14262]
goroutine 35 [running]:
github.com/pulumi/pulumi-command/provider/pkg/provider.(*command).run(0xc000115b90, {0xe0ec20, 0xc00037e680}, {0xc0000dbe78, 0x13}, 0xc0000b3278, {0xc000126770, 0x67})
	/home/runner/work/pulumi-command/pulumi-command/provider/pkg/provider/command.go:136 +0x8c2
github.com/pulumi/pulumi-command/provider/pkg/provider.(*command).RunUpdate(0xc000115b90, {0xe0ec20, 0xc00037e680}, 0x0, {0xc000126770, 0x7})
	/home/runner/work/pulumi-command/pulumi-command/provider/pkg/provider/command.go:67 +0xc8
github.com/pulumi/pulumi-command/provider/pkg/provider.(*commandProvider).Update(0xc0000cd5e0, {0xe0ecc8, 0xc000482150}, 0xc00014d400)
	/home/runner/work/pulumi-command/pulumi-command/provider/pkg/provider/provider.go:311 +0x6a5
github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler.func1({0xe0ecc8, 0xc000482150}, {0xcb2920, 0xc00014d400})
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.34.1/proto/go/provider.pb.go:2658 +0x7b
github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0xe0ecc8, 0xc00035dce0}, {0xcb2920, 0xc00014d400}, 0xc00037c240, 0xc0000b3d58)
	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8[645](https://github.com/gaia-family/monorepo/runs/7077663481?check_suite_focus=true#step:7:648)/go/otgrpc/server.go:57 +0x406
github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler({0xcc1b40, 0xc0000cd5e0}, {0xe0ecc8, 0xc00035dce0}, 0xc0000bf2c0, 0xc0000c3a80)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.34.1/proto/go/provider.pb.go:2[660](https://github.com/gaia-family/monorepo/runs/7077663481?check_suite_focus=true#step:7:663) +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00024f880, {0xe1dff0, 0xc000326b60}, 0xc000480240, 0xc000113d40, 0x13d2170, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00024f880, {0xe1dff0, 0xc000326b60}, 0xc000480240, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:919 +0x294
```

**Comment by jkisk** [comment]
I'll publish a release shortly.

**Comment by stack72** [comment]
@jkisk does v0.3.1 close this out?

**Comment by jkisk** [comment]
I hope so, I wanted to verify there were no further issues before resolving.
